name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CapRover CLI
      run: npm install -g caprover

    - name: Clean Old CapRover Machine
      run: caprover logout -n mycaprover || true

    - name: Login to CapRover
      run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover

    # ✅ Deploy Frontend
    - name: Deploy Frontend
      run: |
        cd frontend
        echo "Deploying frontend from $(pwd)"
        caprover deploy \
          -n new-frontend \
          --caproverName mycaprover

    # ✅ Deploy Go Backend
    - name: Deploy Go Backend
      run: |
        cd backend-go
        echo "Deploying Go backend from $(pwd)"
        caprover deploy \
          -n new-backend-go \
          --caproverName mycaprover

    # ✅ Deploy Python Backend
    - name: Deploy Python Backend
      run: |
        cd backend-python
        echo "Deploying Python backend from $(pwd)"
        caprover deploy \
          -n new-backend-python \
          --caproverName mycaprover
