name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CapRover CLI
      run: npm install -g caprover

    # Deploy Frontend
    - name: Deploy Frontend
      run: |
        caprover login -n captain \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -u http://34.122.198.221
        caprover deploy \
          -n new-frontend \
          -b ./frontend

    # Deploy Go Backend
    - name: Deploy Go Backend
      run: |
        caprover login -n captain \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -u http://34.122.198.221
        caprover deploy \
          -n new-backend-go \
          -b ./backend-go

    # Deploy Python Backend
    - name: Deploy Python Backend
      run: |
        caprover login -n captain \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -u http://34.122.198.221
        caprover deploy \
          -n new-backend-python \
          -b ./backend-python
