name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backendgo: ${{ steps.filter.outputs.backendgo }}
      backendpython: ${{ steps.filter.outputs.backendpython }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Detect changed folders
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          frontend:
            - 'frontend/**'
          backendgo:
            - 'backend-go/**'
          backendpython:
            - 'backend-python/**'

  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g caprover
    - run: caprover logout -n mycaprover || true
    - run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover
    - name: Deploy Frontend
      run: |
        tar -czf frontend.tar.gz frontend
        caprover deploy \
          --appName new-frontend \
          --tarFile ./frontend.tar.gz \
          --caproverName mycaprover

  deploy-backend-go:
    needs: detect-changes
    if: needs.detect-changes.outputs.backendgo == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g caprover
    - run: caprover logout -n mycaprover || true
    - run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover
    - name: Deploy Go Backend
      run: |
        tar -czf backend-go.tar.gz backend-go
        caprover deploy \
          --appName new-backend-go \
          --tarFile ./backend-go.tar.gz \
          --caproverName mycaprover

  deploy-backend-python:
    needs: detect-changes
    if: needs.detect-changes.outputs.backendpython == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g caprover
    - run: caprover logout -n mycaprover || true
    - run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover
    - name: Deploy Python Backend
      run: |
        tar -czf backend-python.tar.gz backend-python
        caprover deploy \
          --appName new-backend-python \
          --tarFile ./backend-python.tar.gz \
          --caproverName mycaprover
