name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend_go: ${{ steps.filter.outputs.backend_go }}
      backend_python: ${{ steps.filter.outputs.backend_python }}
      deploy_all: ${{ steps.check_message.outputs.deploy_all }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Changed Paths
        id: filter
        run: |
          echo "frontend=$(git diff --name-only HEAD~1 HEAD | grep -q '^frontend/' && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "backend_go=$(git diff --name-only HEAD~1 HEAD | grep -q '^backend-go/' && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "backend_python=$(git diff --name-only HEAD~1 HEAD | grep -q '^backend-python/' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Check Commit Message for Deploy All
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"[deploy-all]"* ]]; then
            echo "deploy_all=true" >> $GITHUB_OUTPUT
          else
            echo "deploy_all=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: detect-changes
    strategy:
      matrix:
        app: [frontend, backend-go, backend-python]

    if: |
      needs.detect-changes.outputs.deploy_all == 'true' ||
      (matrix.app == 'frontend' && needs.detect-changes.outputs.frontend == 'true') ||
      (matrix.app == 'backend-go' && needs.detect-changes.outputs.backend_go == 'true') ||
      (matrix.app == 'backend-python' && needs.detect-changes.outputs.backend_python == 'true')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js for CapRover CLI
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy App
        run: |
          if [ "${{ matrix.app }}" == "frontend" ]; then
            APP_NAME="${{ secrets.CAPROVER_FRONTEND_APP }}"
            APP_DIR="frontend"
          elif [ "${{ matrix.app }}" == "backend-go" ]; then
            APP_NAME="${{ secrets.CAPROVER_BACKEND_GO_APP }}"
            APP_DIR="backend-go"
          else
            APP_NAME="${{ secrets.CAPROVER_BACKEND_PYTHON_APP }}"
            APP_DIR="backend-python"
          fi

          cd $APP_DIR
          caprover deploy \
            --caproverUrl "${{ secrets.CAPROVER_URL }}" \
            --appName "$APP_NAME" \
            --password "${{ secrets.CAPROVER_PASSWORD }}" \
            --branch main
