name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CapRover CLI
      run: npm install -g caprover

    - name: Clean Old CapRover Machine
      run: caprover logout -n mycaprover || true

    - name: Login to CapRover
      run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover

    # ✅ Deploy Frontend
    - name: Deploy Frontend
      run: |
        echo "Packaging frontend..."
        tar -czf frontend.tar.gz -C frontend .
        echo "Deploying frontend..."
        caprover deploy \
          --appName new-frontend \
          --tarFile ./frontend.tar.gz \
          --caproverName mycaprover

    # ✅ Deploy Go Backend
    - name: Deploy Go Backend
      run: |
        echo "Packaging Go backend..."
        tar -czf backend-go.tar.gz -C backend-go .
        echo "Deploying Go backend..."
        caprover deploy \
          --appName new-backend-go \
          --tarFile ./backend-go.tar.gz \
          --caproverName mycaprover

    # ✅ Deploy Python Backend
    - name: Deploy Python Backend
      run: |
        echo "Packaging Python backend..."
        tar -czf backend-python.tar.gz -C backend-python .
        echo "Deploying Python backend..."
        caprover deploy \
          --appName new-backend-python \
          --tarFile ./backend-python.tar.gz \
          --caproverName mycaprover
