name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CapRover CLI
      run: npm install -g caprover

    - name: Clean Old CapRover Machine
      run: caprover logout -n mycaprover || true

    - name: Login to CapRover
      run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover

    - name: Verify CapRover Login
      run: |
        echo "Listing apps to verify login..."
        caprover list apps

    - name: Deploy Frontend
      run: |
        caprover deploy \
          -n new-frontend \
          -b ./frontend \
          --caproverName mycaprover

    - name: Deploy Go Backend
      run: |
        caprover deploy \
          -n new-backend-go \
          -b ./backend-go \
          --caproverName mycaprover

    - name: Deploy Python Backend
      run: |
        caprover deploy \
          -n new-backend-python \
          -b ./backend-python \
          --caproverName mycaprover
