name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CapRover CLI
      run: npm install -g caprover

    - name: Clean Old CapRover Machine
      run: caprover logout -n mycaprover || true

    - name: Login to CapRover
      run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover

    # Deploy Frontend
    - name: Deploy Frontend
      run: |
        FRONTEND_PATH=$(pwd)/frontend
        echo "Deploying from $FRONTEND_PATH"
        caprover deploy \
          -n new-frontend \
          -d $FRONTEND_PATH \
          --caproverName mycaprover

    # Deploy Go Backend
    - name: Deploy Go Backend
      run: |
        GO_PATH=$(pwd)/backend-go
        echo "Deploying from $GO_PATH"
        caprover deploy \
          -n new-backend-go \
          -d $GO_PATH \
          --caproverName mycaprover

    # Deploy Python Backend
    - name: Deploy Python Backend
      run: |
        PY_PATH=$(pwd)/backend-python
        echo "Deploying from $PY_PATH"
        caprover deploy \
          -n new-backend-python \
          -d $PY_PATH \
          --caproverName mycaprover
