name: Deploy to CapRover

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Install CapRover CLI
    - name: Install CapRover CLI
      run: npm install -g caprover

    # 3. Clean Old CapRover Machine (if exists)
    - name: Clean Old CapRover Machine
      run: caprover logout -n mycaprover || true

    # 4. Login to CapRover
    - name: Login to CapRover
      run: |
        caprover login \
          -u https://captain.34.122.198.221.nip.io \
          -p ${{ secrets.CAPROVER_PASSWORD }} \
          -n mycaprover

    # 5. Verify Login (Debug Step)
    - name: Verify CapRover Login
      run: |
        echo "Listing apps to verify login..."
        caprover list apps --caproverName mycaprover

    # 6. Deploy Frontend
    - name: Deploy Frontend
      run: |
        caprover deploy \
          -n new-frontend \
          -b ./frontend \
          --caproverName mycaprover

    # 7. Deploy Go Backend
    - name: Deploy Go Backend
      run: |
        caprover deploy \
          -n new-backend-go \
          -b ./backend-go \
          --caproverName mycaprover

    # 8. Deploy Python Backend
    - name: Deploy Python Backend
      run: |
        caprover deploy \
          -n new-backend-python \
          -b ./backend-python \
          --caproverName mycaprover
